### ISSUE TITLE
'reid.datasets' is missing

### ISSUE THREAD

**Issue by xxchenxx** [yxgeee/FD-GAN#1]
I found no `datasets` in folder `reid`. Should I install package 'open-reid' or just copy the folder from that repo?
Thanks.

**Comment by yxgeee** [comment]
Please download the datasets with prepared pose landmarks following **Dataset** in **README**.
And you can change the root of datasets by changing argments in baseline.py (for baseline training) and fdgan/options.py (for fdgan training).
FD-GAN and reid baseline share the same datasets.

You do not need to install package 'open-reid', and do not need to copy files from that repo. Since I have modified it.

**Comment by xxchenxx** [comment]
Thanks for replying.
I have followed your instructions in readme file, downloaded dataset Market1501 and extracted it. But it didn’t solve the problem. 
I was wondering if you could check whether some code files are missing since for now I have copied the directory ‘datasets’ from ‘open-reid’ and the error was gone.

**Comment by yxgeee** [comment]
Thanks. 
I missed `reid.datasets` due to the bug in `.gitignore`.
I have fixed it. Please check.

**Comment by xxchenxx** [comment]
Thanks again.
