### ISSUE TITLE
'resume' in train.py

### ISSUE THREAD

**Issue by QingzeYin** [yxgeee/FD-GAN#7]
Hi, I found that you only have `-- resume` in `baseline.py`, not in `train.py`. There is an error about there does not exist `load_checkpoint` in `train.py` when I am doing the stage3. So I added `import load_checkpoint` in `train.py`. However, I cannot use `-- resume` to do the loading checkpoints part. So I wanna ask where I can add the _load from checkpoint_ part in `train.py` ? Is that before _for epoch_ or after that ?
 this screenshots below show the _load from checkpoint_ part you wrote in `baseline.py`. Can I use this part in `train.py` ?
![screenshot from 2018-11-08 15-53-46](https://user-images.githubusercontent.com/38550460/48185177-367f7d80-e36f-11e8-9329-0c245382010e.png)

**Comment by yxgeee** [comment]
I load the pretrained model here:
https://github.com/yxgeee/FD-GAN/blob/master/fdgan/model.py#L60

**Comment by QingzeYin** [comment]
but I cannot continue running without `resume`. so do you think there no need to add `resume` in `train.py`?

**Comment by yxgeee** [comment]
I have not tried to continue training, since I run the code in an end-to-end manner in each stage.
I am not sure whether continuing running affects the final performance or not, maybe you can try it.

You can add the `resume` following `baseline.py`, but notice to save the state_dict of optimizer meanwhile, since it has influence on training.

**Comment by QingzeYin** [comment]
I wanted to copy the content in the last screenshot into `train.py` and not found optimizer here. So would you mind tell me where is the `state_dict` of optimizer ?

**Comment by yxgeee** [comment]
Directly copying the continuing training code in the `baseline.py` is not suitable, since we have four models in FD-GAN, please carefully refer to 
https://github.com/yxgeee/FD-GAN/blob/master/fdgan/model.py
Notice the `model` in `train.py` is a class, not a `Module` in pytorch. 

About how to save and load the state dict of optimizer, you can refer to 
https://github.com/pytorch/examples/blob/master/imagenet/main.py#L192

**Comment by QingzeYin** [comment]
thanks your answers. I am going to try it:D

**Comment by iskenderkahramanoglu** [comment]
Hi, I want to resume my training from the last checkpoint. Did you solve this problem?
If you solved it, can you explain me? Thanks. @QingzeYin @yxgeee

**Comment by QingzeYin** [comment]
Sorry, can't do anything to help you.
